### ISSUE TITLE
libiscsi

### ISSUE THREAD

**Issue by phatina** [mikechristie/open-iscsi#14]
Hi,

I'd like to ask for formal requirements, so that you (as upstream) would include libiscsi into the source tree? I am talking about [libiscsi](https://github.com/phatina/open-iscsi/tree/master/libiscsi) which currently lives only in Fedora's dist git (this repo also contains Fedora's patches).

Thank you very much.

**Comment by mikechristie** [comment]
Please post your question to open-iscsi@googlegroups.com. Most of the iscsi developers are not on github.
